---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: travel website
    app.kubernetes.io/component: travel website
    app.kubernetes.io/part-of: travel website
  name: travel website
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: travel website.
  template:
    metadata:
      labels:
        app.kubernetes.io/name: travel website.
      name: 
    spec:
      containers:
      - name: 
        image: #
        imagePullPolicy: IfNotPresent
        env:
          - name: LIBBPFGO_OSRELEASE_FILE
            value: /etc/os-release-host
        securityContext:
          privileged: true
        volumeMounts:
        - name: travel website
          mountPath: ..\travel\website
        - name: etc-os-release
          mountPath: /etc/os-release-host
          readOnly: true
        
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
      );